# Generated by Django 3.2.6 on 2021-09-01 04:58

from django.db import migrations, models
import modules.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qrcode',
            field=models.CharField(default=modules.core.utils.get_default_uuid, max_length=36, unique=True),
        ),
    ]
