# Generated by Django 4.0.1 on 2022-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qrcode_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
