# Generated by Django 3.2.4 on 2021-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='<function uuid4 at 0x7f374a66ec10>', max_length=64, unique=True),
        ),
    ]
