# Generated by Django 3.2.6 on 2021-09-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsistenciaBasica',
        ),
    ]
