# Generated by Django 3.2.6 on 2021-09-01 05:03

from django.db import migrations, models
import modules.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_asistenciabasica'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qrcode',
            field=models.CharField(default=modules.core.utils.get_default_uuid, max_length=36),
        ),
    ]
