# Generated by Django 4.0.1 on 2022-01-10 15:32

from django.db import migrations, models
import modules.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qrcode_photo',
            field=models.ImageField(blank=True, null=True, upload_to=modules.core.utils.get_filename),
        ),
    ]
