# Generated by Django 4.0.1 on 2022-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_qrcode_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qrcode_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='qrcode_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
