# Generated by Django 3.2.6 on 2021-08-10 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_name', models.CharField(max_length=8, unique=True)),
                ('en_name', models.CharField(max_length=8, unique=True)),
                ('day_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
