# Generated by Django 3.2.4 on 2021-07-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseopening',
            name='price',
            field=models.FloatField(default=20),
        ),
    ]
